# Generated by Django 5.1.2 on 2024-10-24 21:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(choices=[('OS', 'Medicines possibly out of stock in the next week'), ('SH', 'Medicines currently in shortage'), ('PS', 'Medicines possibly in shortage next week')], max_length=2)),
                ('severity', models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], max_length=1)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('data', models.JSONField()),
                ('total', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sows', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('eows', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('sales', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('total_sales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sowd', models.DateField()),
                ('eowd', models.DateField()),
                ('shortage', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=100)),
                ('form', models.CharField(max_length=100)),
                ('substances', models.CharField(max_length=200)),
                ('statutAMM', models.CharField(choices=[('AMME', 'AMM Enregistrée'), ('AMMR', 'AMM Retirée')], max_length=4)),
                ('statutCommercialisation', models.CharField(choices=[('C', 'Commercialisé'), ('NC', 'Non Commercialisé'), ('RM', 'Retiré du Marché'), ('C/AO', 'Commercialisé / appel d offre')], max_length=4)),
                ('presentation', models.CharField(max_length=100)),
                ('pp_gn', models.CharField(choices=[('GN', 'Générique'), ('PP', 'Produit Propriétaire')], max_length=2)),
                ('class_therapeutique', models.CharField(max_length=250)),
                ('EPI', models.CharField(max_length=150)),
                ('PPV', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PH', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PFHT', models.DecimalField(decimal_places=2, max_digits=10)),
                ('code_ATC', models.CharField(max_length=10)),
                ('TVA', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('shortages', models.JSONField()),
                ('sales', models.JSONField()),
                ('stock_predictions', models.JSONField()),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('reorderPoint', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('lastReorderDate', models.DateField(blank=True, null=True)),
                ('sellingSpeed', models.CharField(choices=[('VS', 'Very Slow'), ('S', 'Slow'), ('M', 'Medium'), ('F', 'Fast'), ('VF', 'Very Fast')], default='S', max_length=2)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.drug')),
            ],
        ),
        migrations.RemoveField(
            model_name='sale',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='amount',
        ),
        migrations.AddField(
            model_name='sale',
            name='quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='sale',
            name='time',
            field=models.TimeField(blank=True, default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='drug',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.drug'),
        ),
        migrations.AddField(
            model_name='archive',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.stock'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
