# Generated by Django 5.1.2 on 2024-10-24 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alert_archive_drug_report_stock_remove_sale_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='total_sales',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
