# Generated by Django 5.1.2 on 2024-10-24 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_archive_total_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='total_sales',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
