# Generated by Django 5.1.2 on 2024-10-25 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_sale_drug'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='drug',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.drug'),
        ),
    ]
