# Generated by Django 5.1.2 on 2024-10-25 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_sale_drug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='time',
        ),
    ]
