# Generated by Django 5.1.2 on 2024-10-25 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_sale_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.drug'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='sale',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
