# Generated by Django 5.1.2 on 2024-11-30 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_remove_archive_total_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sale',
            name='drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.drug'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sale',
            name='time',
            field=models.TimeField(),
        ),
    ]
