# Generated by Django 5.1.2 on 2024-11-30 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_sale_date_alter_sale_drug_alter_sale_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.drug'),
        ),
    ]
