// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMM6-BozooRMUk-c_rbuwxdOrZnFRFkzw',
    appId: '1:1005094900563:web:4c916216159cef55d587a6',
    messagingSenderId: '1005094900563',
    projectId: 'curavisionai',
    authDomain: 'curavisionai.firebaseapp.com',
    storageBucket: 'curavisionai.firebasestorage.app',
    measurementId: 'G-YBNRH3LNWZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSjFGkja_vBQZzPvjhfgG-HM0muQ26HW0',
    appId: '1:1005094900563:android:ddbbf29b09a9ac65d587a6',
    messagingSenderId: '1005094900563',
    projectId: 'curavisionai',
    storageBucket: 'curavisionai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9e4_P02romhyt3J0LsNJPE08PM_wq_mg',
    appId: '1:1005094900563:ios:c69cdf4a4450ff50d587a6',
    messagingSenderId: '1005094900563',
    projectId: 'curavisionai',
    storageBucket: 'curavisionai.firebasestorage.app',
    iosBundleId: 'com.example.curavisionai',
  );
}
